#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Oct 14 21:56:19 2014
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ExceptionViewer(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ExceptionViewer.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.btnClear = wx.Button(self, wx.ID_ANY, u"\u041e\u0447\u0438\u0441\u0442\u0438\u0442\u044c")
        self.btnSave = wx.Button(self, wx.ID_ANY, u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c...")
        self.btnLoad = wx.Button(self, wx.ID_ANY, u"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c")
        self.listExceptions = wx.ListBox(self, wx.ID_ANY, choices=[], style=wx.LB_SINGLE)
        self.textException = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY | wx.HSCROLL)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btnClear_onclick, self.btnClear)
        self.Bind(wx.EVT_BUTTON, self.btnSave_onclick, self.btnSave)
        self.Bind(wx.EVT_BUTTON, self.btnLoad_onclick, self.btnLoad)
        self.Bind(wx.EVT_LISTBOX, self.listExceptions_onselect, self.listExceptions)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ExceptionViewer.__set_properties
        self.SetTitle(u"\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u0438\u0441\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0439")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ExceptionViewer.__do_layout
        sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_1.Add(self.btnClear, 0, 0, 0)
        grid_sizer_1.Add(self.btnSave, 0, 0, 0)
        grid_sizer_1.Add(self.btnLoad, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, 0, 0)
        sizer_1.Add(self.listExceptions, 0, wx.EXPAND, 0)
        sizer_1.Add(self.textException, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.AddGrowableRow(1)
        sizer_1.AddGrowableRow(2)
        sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def btnClear_onclick(self, event):  # wxGlade: ExceptionViewer.<event_handler>
        print "Event handler 'btnClear_onclick' not implemented!"
        event.Skip()

    def btnSave_onclick(self, event):  # wxGlade: ExceptionViewer.<event_handler>
        print "Event handler 'btnSave_onclick' not implemented!"
        event.Skip()

    def btnLoad_onclick(self, event):  # wxGlade: ExceptionViewer.<event_handler>
        print "Event handler 'btnLoad_onclick' not implemented!"
        event.Skip()

    def listExceptions_onselect(self, event):  # wxGlade: ExceptionViewer.<event_handler>
        print "Event handler 'listExceptions_onselect' not implemented!"
        event.Skip()

# end of class ExceptionViewer
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = ExceptionViewer(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()